### ISSUE TITLE
Remove anonymize grants contributions option

### ISSUE THREAD

**Issue by lthrift** [gitcoinco/gitcoinco#151]
This functionality no longer works or is supported and needs to be removed from the a user's options.

Details here: https://discord.com/channels/562828676480237578/1022430992012677121/1022430994411814922

**Comment by thelostone-mc** [comment]
Assiging this to @vacekj! Can't seem to tag him in the issue and hence the comment

**Comment by lthrift** [comment]
@thelostone-mc i have the backlog prioritized. It would be great if we could be sure to work of the top of the backlog please 🙏
