### ISSUE TITLE
Rejecting didn't work

### ISSUE THREAD

**Issue by abitrolly** [gitcoinco/gitcoinco#17]
On this issue https://gitcoin.co/funding/process?source=https://github.com/open-eid/linux-installer/issues/13

I tried to Reject issue and gitcoin.co generated transaction in Metamask with 5 Wei price. It was present at https://etherscan.io/tx/0x33eeecd053e4e4509d5c5cb4129363bbc5aa7a00c11c0a90dc767ac889b31cb6 but then gone.

I tried to increase the price to 7, but transaction didn't reappear. So I then rejected transaction and repeated Reject process for issue with higher gas price.

New transaction is confirmed
https://etherscan.io/tx/0x0a5b9fe71b69fc2880911fe760a1aca580a8bd18e04b3e5da6dd8 but the issue is not rejected https://gitcoin.co/funding/details?url=https://github.com/open-eid/linux-installer/issues/13

**Comment by abitrolly** [comment]
Affects process over https://github.com/open-eid/linux-installer/issues/13

**Comment by owocki** [comment]
i get an "Invalid TxHash  0x0a5b9fe71b69fc2880911fe760a1aca580a8bd18e04b3e5da6dd8  entered" when i click https://etherscan.io/tx/0x0a5b9fe71b69fc2880911fe760a1aca580a8bd18e04b3e5da6dd8

**Comment by owocki** [comment]
@abitrolly  i just went in and synced https://gitcoin.co/funding/details?url=https://github.com/open-eid/linux-installer/issues/13 wit hthe blockchain. the rejection has processed now!

root cause fix for this is being tracked at https://github.com/gitcoinco/web/issues/128

**Comment by owocki** [comment]
ok to close this issue now?  thanks for the bug report :)

**Comment by abitrolly** [comment]
https://etherscan.io/tx/0x0a5b9fe71b69fc2880911fe760a1aca580a8bd18e04b3e5da6dd8e1ca55b0a7f - its tail was stripped. It is ok now. Subscribed to https://github.com/gitcoinco/web/issues/128
