### ISSUE TITLE
Mission: Push Open Source Forward vs Grow Open Source

### ISSUE THREAD

**Issue by owocki** [gitcoinco/gitcoinco#21]
I've been delberating the mission recently... 

It was originally

# Push Open Source Forward

![phrases-11](https://user-images.githubusercontent.com/513929/34880265-2b780568-f76d-11e7-8bbf-e23a0c0149a8.png)
![pushossfwd](https://user-images.githubusercontent.com/513929/34880269-2e18638a-f76d-11e7-8787-80018975471a.jpg)

but I am contemplating whether we should change it to 

# Grow Open Source

![art_dark](https://user-images.githubusercontent.com/513929/34880300-45321930-f76d-11e7-9813-1ffc8527196f.png)
![gitcoin_artwork02_final-v2](https://user-images.githubusercontent.com/513929/34880304-4951b714-f76d-11e7-9b38-fc7a24d0a9cf.gif)

# Why 

1. It's more concise
2. "Push" to me denotes exerting a ton of effort.. possible uphill.  Every time I've tried to 'push' a software project forward, I meet resistance in the form of friction...  Whereas 'grow' seems to be more of the action that actually enables the seeds of an open source to be successful (to grow and thrive).. in that its a little effort, care, and thoughtfulness here and there over a long time.
3. 'Grow' denotes nature in my mind, and ... lets face it I live in Boulder Colorado so I must love the outdoors :) 
4. The artwork is cooler.

**Comment by owocki** [comment]
@coderberry @mbeacom @vs77bb @pixelantdesign @kamecg @thelostone-mc @tra38 @ethikz @amites  curious what you think!  and please tell me what you _really_ think, like it or not!

**Comment by tra38** [comment]
- When I hear "push open source", I don't really know what you're talking about (sure, you say "push"...but "pushing" open source to do *what*, exactly?). So I have to dig deeper to find out what Gitcoin is. 
- When I hear "grow open source", I think the phrase means "increase the usage/domination/adoption/proliferation of open source projects within society". That could be an appealing goal for some people, but not for me, as "open source" itself steadily growing anyway, even if specific projects aren't receiving the care and maintenance that they need. But this integration of the quote doesn't appear to reflect the message you intended to convey.

So my suggestion is to add one word to the mission statement to avoid confusion: "Grow Open Source Projects". But that's just my opinion.

>"Push" to me denotes exerting a ton of effort.. possible uphill. Every time I've tried to 'push' a software project forward, I meet resistance in the form of friction...

I actually do like the term "Pushing Open Source Projects" for that reason too. Software development is a "wicked problem" where it is difficult to know exactly how long it will take. But I can understand if you want to use a more optimistic phrase to describe what is being done here.

**Comment by amites** [comment]
_pre-coffee thoughts_

grow open source sounds/feels like an organic inclusive process, "come get involved and let's make this better together"

push open source sounds/feels like effort, your thoughts on meeting resistance when pushing hits the nail on the head

and yeah, the logo is cooler -- original seems like you're in a race the "tree" comes back to "make something bigger together"

**Comment by vs77bb** [comment]
@tra38 Your perspective helps me frame my thoughts. I am +1 on "Growing Open Source" or a variant over "Push Open Source Forward." However, I think it's important to explain what someone is doing when they Grow Open Source (in a content piece to come). 

- Directly contribute to the collective consciousness of the internet  
- Can immediately improve systems which affect millions of lives
- Allow the middle/small size repo, maintained by 1-2 people, to maintain itself through the crowd 

I like "Grow Open Source" for simplicity and to leave things a bit open-ended :)

**Comment by mbeacom** [comment]
I am 👍 for: `"Grow Open Source"`

@tra38 makes some valid points regarding the optimistic leaning and implicit nature of growing versus pushing. 
However, I'm inclined to agree with @vs77bb.
I think the simplicity and generality of "Grow Open Source" make for an enticing mission statement.

**Comment by thelostone-mc** [comment]
+1 Grow open source

Everyone here covered whatever I wanted to say!
@mbeacom 
And yes it's a more positive mission statement. ( To me the word grow feels inviting unlike push which feels like it's being forced upon. 
Also in my head, when you say Grow Open Source = Community grows = You grow and meet smarter folks = exciting  ) 

PS : the artwork is neat :D

**Comment by owocki** [comment]
seems like 'grow open source' is the crowd favorite.  closing this now.. we should migrate the imagery/copy over soon.
