### ISSUE TITLE
Github access level for the Gitcoin app

### ISSUE THREAD

**Issue by axic** [gitcoinco/gitcoinco#24]
Sorry if I am ignorant and writing this at a the wrong place.

Why does the gitcoin Github App needs write permissions to user details?

> This application will be able to read and write all user data. This includes the following:
> Private email addresses
> Private profile information
> Followers

**Comment by owocki** [comment]
hey @mbeacom i thought we changed this to no longer need write access?

**Comment by mbeacom** [comment]
@owocki Looks like our environment specific setting files are overriding the `GITHUB_SCOPE`.  Pushing an update now!

**Comment by mbeacom** [comment]
@axic This has been resolved.  Please reload `https://gitcoin.co` and re-authenticate.
Thanks for the heads up!

**Comment by axic** [comment]
Thank you, it works! :)
