### ISSUE TITLE
Provide "Prerequisites for Claiming/Finishing Work" document / link

### ISSUE THREAD

**Issue by lazaridiscom** [gitcoinco/gitcoinco#27]
In order to avoid disappointed new users (see #26), the following steps should be taken:

* Provide a document, **written by a newcomer** to crypto-currency, which describes in a compact and clear manner the relevant knowledge and steps.

* When MetaMask is not installed, show a text like "Prerequisites for Submitting Work to collect bounties" with a link to the document.

* Really Really: provide an option thus one can "shoot the fox" (make the fox stop moving his head).

I am new to the domain, so I could write the document (would need an edit from an native english speaker though...)

**Comment by owocki** [comment]
i think gitcoin.co/onboard is the closest to this that we have now

**Comment by lazaridiscom** [comment]
That's too big, and hosted on gdocs (makes a strange impression). Something really tiny. if I need a break from code-level tonight, I'll give it a try.

**Comment by lazaridiscom** [comment]
This system is beta-software, which is designed for users which are familiar with crypto-currencies (cc. You can obtain the necessary knowledge quite fast: 

There are different crypto-currencies out there, the most know is "bitcoin". Gitcoin sound like a currency, too - but its not!

Gitcoin.co uses Ether (of the Ethereum Project). In order to work with Ether, you need a Wallet. Once you are familiar with this, then you can go on to the next steps.

For the Gitcoin.co system to operate you need to have a special Wallet, right within your browser. This is provided by MetaMask. You can install MetaMask as an addon, and then either create a new account, or import an existent account (from a standard, non-browser wallet).

Please be aware that if you "Start Work" and leave all this for after the coding-work, you risk to get overwhelmed and frustrated by trying to grasp all this and setup things to get your bounty (your payment).

So, just ensure that you have understood and setup things right. And then, enjoy your work and your bounties!

Resources with helpful folks:

* x
* y
* z

**Comment by lazaridiscom** [comment]
Followup #25
