### ISSUE TITLE
C-level Bounties (Real Example: Post Mortem Analysis)

### ISSUE THREAD

**Issue by lazaridiscom** [gitcoinco/gitcoinco#31]
Please review this one, to get an idea about a new category of tasks / bounties:

MetaMask/metamask-extension/issues/3247

Its a real use case. This issue was a bounty itself, But the most important thing would be what is done after.

**Comment by owocki** [comment]
I'm a big fan of the 'five whys' type analysis and in general 'fix it twice' mantra.  its fun to see that done in a new format / in a distributed way

**Comment by lazaridiscom** [comment]
Seems we agree here (although I've follow usually a "free-dynamic" process, mainly oriented towards "barriers", but ok, that's another topic).

As for gitcoin, the **actions** could be:

- => Specify high-experience (senior/chief/director grade) task categories (e.g.: "C-level")
- => Provide a text to inform funders about the importance of such tasks/bounties

The (broader scope) thing is:

If open-source / open-work is to take over as the absolute no 1 development model, then it is essential to organize the C-level tasks, too. Simply because C-level folks needs 2nd opinions and assistance, too. And high-performers need to find some difficult tasks on gitcoin, too.
