### ISSUE TITLE
Problem with submitted Faucet request 

### ISSUE THREAD

**Issue by UnrealCity** [gitcoinco/gitcoinco#39]
I submitted a Faucet request but was not able to add my ETH address. What can I do to submit my address?

**Comment by mbeacom** [comment]
@UnrealCity Sorry to hear about your troubles!

Which browser? Were you actively logged into MetaMask on the browser being used?

**Comment by UnrealCity** [comment]
Yes, I was logged into MetaMask. I just added the extension yesterday.

**Comment by UnrealCity** [comment]
It appears the ETH has been deposited to my MetaMask.  So MetaMask has it's
own ETH address. I guess that's the part I didn't understand. I assumed I
needed to input ETH address for my Ethereum wallet.

**Comment by owocki** [comment]
> So MetaMask has it'sown ETH address.

Yup!  We may need to adjust the FTUX here to do a little better job explaining metamask :)

**Comment by UnrealCity** [comment]
Thanks for the quick response. I think I understand how it works now.

**Comment by mbeacom** [comment]
@UnrealCity Thanks for reaching out! Let us know if you have any further questions or recommendations! 

Feel free to join us on slack:  https://gitcoin.co/slack
