### ISSUE TITLE
Feature request: ability to top up bounties

### ISSUE THREAD

**Issue by pascalvanhecke** [gitcoinco/gitcoinco#40]
There seems to be no way to add more ETH to an existing bounty 

(screenshot indicating where I would have expected a visual cue on how to top up the bounty).

![create visually customizable keyring format metamask funded issue detail gitcoin gitcoin 2018-03-31 02-13-00](https://user-images.githubusercontent.com/290665/38157664-3d210d38-3489-11e8-8464-25941cbb7d66.png)

**Comment by owocki** [comment]
if you are the submitter of an issue, you will see this button for topping up an issue:

[screenshot](http://bits.owocki.com/1a09191e421s/Screen%20Shot%202018-04-02%20at%2011.34.16%20AM.png)



@pascalvanhecke do you see this button on your issues that you create?

**Comment by owocki** [comment]
IIRC, this is not possible in the current version of standardbounties becasue this method ( https://github.com/Bounties-Network/StandardBounties/blob/master/contracts/StandardBounties.sol#L477 ) can only be called by the funder.

cc @mbeylin in case he can think of any workarounds, or perhaps as feedback for him as he scopes v2 of standardbounties

**Comment by owocki** [comment]
@pascalvanhecke this is live now https://medium.com/gitcoin/crowdfunding-bounties-fd821b04309d
