### ISSUE TITLE
States "please review questions" - but there are no questions

### ISSUE THREAD

**Issue by ligi** [gitcoinco/gitcoinco#48]

**Comment by owocki** [comment]
sorry, whats this in reference to?

**Comment by ligi** [comment]
pressed enter to early - wanted to upload this:

![selection_084](https://user-images.githubusercontent.com/111600/41623528-56ea647a-7413-11e8-9ea4-2ca03d59af8e.png)

**Comment by owocki** [comment]
thanks

**Comment by owocki** [comment]
moved over to the web repo at https://github.com/gitcoinco/web/issues/1509
