### ISSUE TITLE
Unreadable dark text over dark background

### ISSUE THREAD

**Issue by pmaojo** [gitcoinco/gitcoinco#54]

**Comment by pmaojo** [comment]
Home footer. Screen capture later

**Comment by thelostone-mc** [comment]
@pmaojo mind opening the issues for our web project over at https://github.com/gitcoinco/web ? 
Would be easier to track and that's usually where the whole community is active ^_^

PS : Could you throw in a screenshot too to give a bit more clarity on the issue ?
