### ISSUE TITLE
Grant hidden from search

### ISSUE THREAD

**Issue by snailking** [gitcoinco/gitcoinco#58]
I received a grant for my game Eggforce from the POA Games Fund last month: https://gitcoin.co/grants/92/eggforce-new-idle-game-on-poa-core-2

However, unless you have the direct URL, it seems hidden from search. Instead, a search for "Eggforce" redirects to this page: https://gitcoin.co/grants/90/eggforce

Which is possibly an earlier grant siddigzeidan initiated, before moving to the newest one.

Would it be possible to swap the two grants around, for the funded one to show up on Grants Explorer and search?

**Comment by snailking** [comment]
I'm also left wondering: will this exclude the grant from CLR matching?

**Comment by owocki** [comment]
resolved via email :)
