### ISSUE TITLE
Appearently incorrect gas cost by 10 times on Grant Submission page

### ISSUE THREAD

**Issue by tjayrush** [gitcoinco/gitcoinco#67]
It appears that the gas fee presented on the GitCoin Grants submission page is reporting incorrect gas costs by a factor of ten as seen in this screen shot.

<img width="1747" alt="Screen Shot 2019-12-03 at 8 51 36 PM" src="https://user-images.githubusercontent.com/5417918/70105854-17096180-1610-11ea-8f86-4a13729e9fc9.png">

**Comment by owocki** [comment]
thanks TJ - copying this  issue over to the web repo... https://github.com/gitcoinco/web/issues/5591

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/commit/f2f9dfdc01def11fb6691f8ea693036bb3b2c210 should fix this
