### ISSUE TITLE
Number of contributors mentioned on the preview differs from actual (?) ones on detailed page

### ISSUE THREAD

**Issue by krrisis** [gitcoinco/gitcoinco#73]
When I take the preview of the Commons Stack page I see 99 Contributors: 

![image](https://user-images.githubusercontent.com/6533925/73000867-d359f980-3e01-11ea-93ef-3187760faec0.png)

When I go to the detail [here](https://gitcoin.co/grants/277/commons-simulator-modeling-sustainable-funding-for?tab=contributors) I see 110 contributors. Which one is correct? I gather the second one bcs it's also what is mentioned on the front of the preview card. I see this difference is there for all of the grants, not only in the example. Noticed during the previous round as well. 

![image](https://user-images.githubusercontent.com/6533925/73001012-0dc39680-3e02-11ea-8817-ea27bb6068f0.png)

**Comment by owocki** [comment]
thanks! mind posting this to https://github.com/gitcoinco/web/issues ?

**Comment by krrisis** [comment]
done
