### ISSUE TITLE
Kudos

### ISSUE THREAD

**Issue by miscreant1** [gitcoinco/gitcoinco#84]
Hey, ive noticed i havent received 8 of my kudos from quests even though same inbox and not 8 in a row just 8 out of 43... I know about the double coin symbol for 2 of the same and those are in my inventory... Any recommendations helpful... Thanks

**Comment by owocki** [comment]
do you know which kudos are missing? do you have a txid for any of them?

**Comment by miscreant1** [comment]
Hey, here are the ones that show up as delivered on my payments screen but
not in the kudos screen or wallet. Also, dont have the tracking numbers but
i have the time passed (as of 5:30pm California time)
Eth Guru- 1 day 4 hours
Firedog- 1 day 16 hours
Above and beyond - 1 day 16 hours
Turing Talker- 1 day 16 hours
Future City - 1 day 16 hours
Open source Freedom Fighter - 6 days 5 hours

1 was a diamond but its out of print so thats not important and the last
one im not too sure its one of the common ones that i have multiples of so
not sure which one wasnt delivered.

**Comment by miscreant1** [comment]
So my best guess is that its fraudulent quests started by people trying to gain points hence no validity in the outsourcing... I dont plan on losing my first place position so i will participate in the new quests only for point value for contest but wont collect on the kudos i see as fake... Im pretty sure this is the cause of the original issue which could i guess be closed if you think im correct?? Only other issue would be how to un monetize my intake??

**Comment by miscreant1** [comment]
Aka pull me from ~$400 back to where i apparently should be circa ~$90ish +/-

**Comment by owocki** [comment]
i actually think we may remove the "get points by creating quests" thing soon.  too many crappy quests being created i agree.

if you downvote thecrappy quests, the system will rank them lower + then eventually hide them.
