### ISSUE TITLE
Scam Grant

### ISSUE THREAD

**Issue by versaceaci** [gitcoinco/gitcoinco#94]
Hello gitcoinco.

This grantee is a scam: https://gitcoin.co/grants/238/bankless

Please do not fund them!

It is illegal what they are saying, "Self-Directed crypto IRA in a box
RocketDollar is a Self-Directed Custodian for self-directed retirement funds. And they’re crypto friendly. They setup the LLC and bank account for you. They pre-fill all the faxes and paperwork for funds transfers from your brokerages. They guide you through process. And they have real live humans to help if you get stuck.

I know this because I recently used them to break an IRA out of brokerage jail.

Some things you should know about the process:

The information here was helpful

It takes a while to transfer funds from brokerages—plan for 3-6 weeks

Brokerages can be a pain to work with—one charged me exit fees

It may take some finagling to get your a crypto exchange to open an account in the name of your IRA LLC—RocketDollar has a relationship with Gemini so it’s pretty seamless if you use them

Fees for RocketDollar are $360 + $15 per month—this covers the LLC and bank account too, there were no surprise fees

Special offer: I told RocketDollar I was planning to recommended them and they were so excited they agreed to provide a code to my readers for $50 off signup. They’re also giving a portion of each signup to support this newsletter.

Click here and use coupon code BANKLESS to get $50 off your signup." (https://bankless.substack.com/p/tax-shelter-your-crypto-in-an-ira)

**Comment by owocki** [comment]
hi; thanks for your report.   please use the 'flag' feature on the grant to report it!

**Comment by versaceaci** [comment]
I have flagged it.
