### ISSUE TITLE
[Grants 1147] We want to accept all tokens

### ISSUE THREAD

**Issue by juandaveth** [gitcoinco/gitcoinco#95]
Hey awesome Gitcoin team!

I've created this [grant](https://gitcoin.co/grants/1147/coinosis-get-crypto-for-sharing-your-knowledge) for a project I'm working on. But I configured it to just accept DAI, I would to accept all type of coins. Some funders have told us they want to contribute to our grant.

Thanks in advance for your help!

**Comment by owocki** [comment]
just updated it

**Comment by juandaveth** [comment]
Confirmed! Gracias Kevin 🥇
